locale                   : "en"
url                       : http://127.0.0.1:4000
baseurl                   : ""
# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  tutorials:
    output: true
    permalink: /:collection/:path/

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock