locale                   : "en"
url                      : "https://pages.github.ibm.com/IBM-Verse"
baseurl                  : "/verse-developer-chrome-ext"
# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  tutorials:
    output: true
    permalink: /:collection/:path/
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
