# Copyright IBM Corp. 2016, 2017  All Rights Reserved.

title: IBM Verse Developer Browser Extension

description: >
  "This site contains a tutorial and reference documentation for IBM Verse developer extensions."
baseurl: "/pages/IBM-Verse/verse-developer-chrome-ext" # the url for this documentation site
url: "https://github.ibm.com" # the base hostname & protocol for your site
verse-developer-chrome-ext: "https://github.ibm.com/IBM-Verse/verse-developer-chrome-ext"

name: Tutorials for Verse Extension
markdown: kramdown

collections:
  tutorials:
    output: true
  reference:
    output: true
  document:
    output: true
