# Copyright IBM Corp. 2016  All Rights Reserved.

title: Tutorials for Verse Extension

description: >
  "This site contains Tutorials for Verse Extension"
baseurl: "/pages/IBM-Verse/verse-developer-chrome-ext"
url: "https://git.swg.usma.ibm.com" # the base hostname & protocol for your site
verse-developer-chrome-ext: "https://git.swg.usma.ibm.com/IBM-Verse/verse-developer-chrome-ext"

name: Tutorials for Verse Extension
markdown: kramdown

collections: 
  tutorials:
    output: true