locale: en
url: 'https://ibmverse.github.io'
baseurl: /verse-developer
collections:
  docs:
    output: true
    permalink: '/:collection/:path/'
  tutorials:
    output: true
    permalink: '/:collection/:path/'
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
