# Copyright IBM Corp. 2016  All Rights Reserved.

title: IBM Verse Extensibility

description: >
  "This site contains a tutorial and reference documentation for the IBM Verse extensibility features."
baseurl: "/pages/IBM-Verse/verse-developer-chrome-ext"
url: "https://git.swg.usma.ibm.com" # the base hostname & protocol for your site
verse-developer-chrome-ext: "https://git.swg.usma.ibm.com/IBM-Verse/verse-developer-chrome-ext"

name: Tutorials for Verse Extension
markdown: kramdown

collections: 
  tutorials:
    output: true
  reference:
    output: true